Good and bad examples
silverstripe-terraformers/accessibility-guidelines pull request #3
Opened 2021-10-21 22:33 UTC by aria5305

Some examples to make it even clearer for what was mentioned in the accessibility.md in project skeleton

2021-10-21 23:38 UTC, adrhumphreys requested changes
Mostly grammer/spelling/small things

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +[[toc]]
🤯 nice

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +Without adding the alt tag for contextual image, it could result in people using screen reader technologies missing out on important information.
```suggestion
Without adding the alt tag for a contextual image, it could result in people using screen reader technologies missing out on important information.
```

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +Alt should also be meaningful and describe the image accurately, it's especially important if the image is supplying information
```suggestion
The `alt` attribute should also be meaningful and describe the image accurately, it's especially important if the image is supplying information
```

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +The content that the skip links goes to is linked with an id and it moves the focus to the element with tabindex="-1".
Is `tabindex` required? My understanding was it would from that point onwards interact with that element

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +Skip link should be placed at the top of the page
```suggestion
Because the skip link is placed after the navigation on every page load a user will have to tab through every navigation link
```

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +1. Use `aria-label`, `aria-labelledby` or the `title` attribute to provide a more descriptive accessible name when the text content of the link cannot be changed.
```suggestion
1. Use `aria-label`, `aria-labelledby` or the `title` attribute to provide a more descriptive name when the text content of the link cannot be changed.
```

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +2. All links should the focus style working
```suggestion
2. All links should have focus styling (don't disable the outline without an alternative)
```

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +3. Use the right elements. Links should always be `<a>` and actions should be `<button>`
```suggestion
3. Use the right elements. Links should always be `<a>` elements and actions should be `<button>`
```

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +Would be even better if you could just avoid using non-informative link phrases(i.e."See more", "Click here") as link text.
```suggestion
This would be even better if you could just avoid using non-informative link phrases (i.e."See more", "Click here") as link text.
```

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +If the content of a link includes an img element(icon.etc), check if the icon actually needs the aria-label, the aria-label should also be descriptive
```suggestion
If the content of a link includes an `img` element (e.g. an icon), check if the `img` actually needs the aria-label, the aria-label should also be descriptive
```

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +- Check incorrect `aria-role` has been applied to any buttons.
I don't think we need this item as buttons will always have the same role

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +- `aria-controls` should be added to the button if it controls another component. (i.e. opening nav)
We should add a generic doc about `aria` and how it can be easily misused and some of the misconceptions (e.g. we're actually only adding `aria-controls` for the JAWS screen reader https://a11ysupport.io/tech/aria/aria-controls_attribute)

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +- Check context has been applied to the action/button e.g. `aria-label="my contextual text".`
```suggestion
- If the buttons content does not provide context then check context has been applied to the button `aria-label="my contextual text".`
```

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +When the nav is opened, `aria-exapanded` should be true instead
```suggestion
`aria-expanded` should reflect the state of the `#nav`. Ensure its updated to `true`, when the nav is opened.
```

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +:::
```suggestion
#### :lady_beetle: BAD button example
```html
<a class="button" onclick="runMyJs()">Click me!</a>
<div onclick="runMyJs()">I am a button!</div>
```
:::warning
In both examples we're using elements that are not `<button />` elements to trigger interactions. Screen readers will not be able to tell that the `a` tag is not a link and they will not be able to tell that the `div` is intractable
:::
```

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +Important thing to remember for navigation is that we should also ensure that keyboard shortcuts work for controlling the menu e.g. `esc` key `closes`, `space` key `opens` etc.
```suggestion
When implementing navigation through modal interfaces it's important to remember that you should implement the expected controls:
- `esc` closes the modal
- `tab` will cycle through only the items inside the modal
- `shift + tab` will cycle through in reverse only the items inside the modal
```

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +We should use `aria-label` to help user to distinguish the different nav available, when using `aria-label` on a <a href="https://web.dev/use-landmarks/">landmark element(i.e. nav)</a>, don't include
```suggestion
We should use `aria-label` to help user to distinguish the different `nav` elements available, when using `aria-label` on a <a href="https://web.dev/use-landmarks/">landmark element(i.e. nav)</a>, don't include the word role of the landmark, as screen readers will annouce it afterwards.
```

2021-10-21 23:38 UTC, adrhumphreys commented on docs/getting-started.md
> +`role=”navigation”` is not required on explicit tags like `<nav>`. However older screen readers that do not support HTML5 tags will require it.
If thats the case could we axe this example? I think we shouldn't need to worry about old browsers in this regard

2021-10-21 23:58 UTC, aria5305 commented on docs/getting-started.md
> +The content that the skip links goes to is linked with an id and it moves the focus to the element with tabindex="-1".
Apparently? Got the `tabindex=-1` from the `accessibility.md` 
- Check if a ‘skip link’, is it targeted via ‘#fragment’ and does the target have tabindex=”-1” applied.

and also here https://designsystem.gov.au/components/skip-link/

2021-10-22 00:02 UTC, aria5305 commented on docs/getting-started.md
> +- `aria-controls` should be added to the button if it controls another component. (i.e. opening nav)
Cool, will do that next. Also wow, didn't know aria-controls really is supported by JAWS screen reader only. https://a11ysupport.io/tech/aria/aria-controls_attribute this is cool 🤓

2021-10-22 00:25 UTC, adrhumphreys commented on docs/getting-started.md
> +The content that the skip links goes to is linked with an id and it moves the focus to the element with tabindex="-1".
Oh neat today I learned 🎉

2021-10-22 00:31 UTC, merged